package com.test.ssm.mapper;

import java.util.List;

import com.test.ssm.domain.Detail;
import com.test.ssm.domain.DetailWithBLOBs;

public interface DetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbggenerated
	 */
	int insert(DetailWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbggenerated
	 */
	int insertSelective(DetailWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbggenerated
	 */
	DetailWithBLOBs selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DetailWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(DetailWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table detail
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Detail record);
	

	List<DetailWithBLOBs> getDetailFromUrl(String url);
}