package com.test.ssm.domain;

public class DetailWithBLOBs extends Detail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.download
     *
     * @mbggenerated
     */
    private String download;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.download
     *
     * @return the value of detail.download
     *
     * @mbggenerated
     */
    public String getDownload() {
        return download;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.download
     *
     * @param download the value for detail.download
     *
     * @mbggenerated
     */
    public void setDownload(String download) {
        this.download = download == null ? null : download.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.image
     *
     * @return the value of detail.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.image
     *
     * @param image the value for detail.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.detail
     *
     * @return the value of detail.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.detail
     *
     * @param detail the value for detail.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}