package com.test.ssm.domain;

public class UrlList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_list._id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_list.from
     *
     * @mbggenerated
     */
    private String from;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_list.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url_list.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_list._id
     *
     * @return the value of url_list._id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_list._id
     *
     * @param id the value for url_list._id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_list.from
     *
     * @return the value of url_list.from
     *
     * @mbggenerated
     */
    public String getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_list.from
     *
     * @param from the value for url_list.from
     *
     * @mbggenerated
     */
    public void setFrom(String from) {
        this.from = from == null ? null : from.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_list.title
     *
     * @return the value of url_list.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_list.title
     *
     * @param title the value for url_list.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url_list.url
     *
     * @return the value of url_list.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url_list.url
     *
     * @param url the value for url_list.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}